/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SpeakerService } from "../speaker.service";
import { SpeakerCreateInput } from "./SpeakerCreateInput";
import { Speaker } from "./Speaker";
import { SpeakerFindManyArgs } from "./SpeakerFindManyArgs";
import { SpeakerWhereUniqueInput } from "./SpeakerWhereUniqueInput";
import { SpeakerUpdateInput } from "./SpeakerUpdateInput";
import { SpeakerSummaryFindManyArgs } from "../../speakerSummary/base/SpeakerSummaryFindManyArgs";
import { SpeakerSummary } from "../../speakerSummary/base/SpeakerSummary";
import { SpeakerSummaryWhereUniqueInput } from "../../speakerSummary/base/SpeakerSummaryWhereUniqueInput";

export class SpeakerControllerBase {
  constructor(protected readonly service: SpeakerService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Speaker })
  async createSpeaker(
    @common.Body() data: SpeakerCreateInput
  ): Promise<Speaker> {
    return await this.service.createSpeaker({
      data: {
        ...data,

        conference: data.conference
          ? {
              connect: data.conference,
            }
          : undefined,
      },
      select: {
        bio: true,

        conference: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Speaker] })
  @ApiNestedQuery(SpeakerFindManyArgs)
  async speakers(@common.Req() request: Request): Promise<Speaker[]> {
    const args = plainToClass(SpeakerFindManyArgs, request.query);
    return this.service.speakers({
      ...args,
      select: {
        bio: true,

        conference: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Speaker })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async speaker(
    @common.Param() params: SpeakerWhereUniqueInput
  ): Promise<Speaker | null> {
    const result = await this.service.speaker({
      where: params,
      select: {
        bio: true,

        conference: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Speaker })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSpeaker(
    @common.Param() params: SpeakerWhereUniqueInput,
    @common.Body() data: SpeakerUpdateInput
  ): Promise<Speaker | null> {
    try {
      return await this.service.updateSpeaker({
        where: params,
        data: {
          ...data,

          conference: data.conference
            ? {
                connect: data.conference,
              }
            : undefined,
        },
        select: {
          bio: true,

          conference: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Speaker })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSpeaker(
    @common.Param() params: SpeakerWhereUniqueInput
  ): Promise<Speaker | null> {
    try {
      return await this.service.deleteSpeaker({
        where: params,
        select: {
          bio: true,

          conference: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/speakerSummaries")
  @ApiNestedQuery(SpeakerSummaryFindManyArgs)
  async findSpeakerSummaries(
    @common.Req() request: Request,
    @common.Param() params: SpeakerWhereUniqueInput
  ): Promise<SpeakerSummary[]> {
    const query = plainToClass(SpeakerSummaryFindManyArgs, request.query);
    const results = await this.service.findSpeakerSummaries(params.id, {
      ...query,
      select: {
        createdAt: true,
        embeddings: true,
        id: true,

        speaker: {
          select: {
            id: true,
          },
        },

        summary: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/speakerSummaries")
  async connectSpeakerSummaries(
    @common.Param() params: SpeakerWhereUniqueInput,
    @common.Body() body: SpeakerSummaryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      speakerSummaries: {
        connect: body,
      },
    };
    await this.service.updateSpeaker({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/speakerSummaries")
  async updateSpeakerSummaries(
    @common.Param() params: SpeakerWhereUniqueInput,
    @common.Body() body: SpeakerSummaryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      speakerSummaries: {
        set: body,
      },
    };
    await this.service.updateSpeaker({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/speakerSummaries")
  async disconnectSpeakerSummaries(
    @common.Param() params: SpeakerWhereUniqueInput,
    @common.Body() body: SpeakerSummaryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      speakerSummaries: {
        disconnect: body,
      },
    };
    await this.service.updateSpeaker({
      where: params,
      data,
      select: { id: true },
    });
  }
}
